### ISSUE TITLE
run code on windows with errors

### ISSUE THREAD

**Issue by ramtinmousavi** [MrChenFeng/SSR_BMVC2022#8]
Hi!

Hope you are well, I've seen your paper, and tried to run your code on windows.
but I faced some errors.

Traceback (most recent call last):
  File "C:\PycharmProjects\SSR_new\main_cifar.py", line 312, in <module>
    main()
  File "C:\PycharmProjects\SSR_new\main_cifar.py", line 283, in main
    train(labeled_loader, modified_label, all_loader, encoder, classifier, proj_head, pred_head, optimizer, i, args)    
  File "C:\PycharmProjects\SSR_new\main_cifar.py", line 52, in train
    labeled_train_iter = iter(labeled_trainloader)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PycharmProjects\SSR_new\venv\Lib\site-packages\torch\utils\data\dataloader.py", line 440, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramtin\PycharmProjects\SSR_new\venv\Lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramtin\PycharmProjects\SSR_new\venv\Lib\site-packages\torch\utils\data\dataloader.py", line 1038, in __init__
    w.start()
  File "C:\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 121, in start     
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 224, in _Popen    
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 336, in _Popen    
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\popen_spawn_win32.py", line 94, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\reduction.py", line 60, in dump     
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'SubPolicy.__init__.<locals>.<lambda>'
Traceback (most recent call last):aded
  File "<string>", line 1, in <module>
  File "C:\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main  
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 130, in _main       
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input

**Comment by MrChenFeng** [comment]
Please use GPT/Google/Stackoverflow for code debugging.
